# The best and most customisable drugs plugin on the market.
# Created with love by rndstad.me
# Please leave a 5-star rating on the DrugsRPG spigot page.

## General Settings ##
preferences:
  use-mysql: true
  host: localhost
  port: 3306
  database: drugsrpg_drugs
  username: ""
  password: ""

check-for-updates: true