##########################################################################
#                                                                        #
#    _____                       _____  _____   _____          ___       #
#   |  __ \                     |  __ \|  __ \ / ____|        |__ \      #
#   | |  | |_ __ _   _  __ _ ___| |__) | |__) | |  __    __   __ ) |     #
#   | |  | | '__| | | |/ _` / __|  _  /|  ___/| | |_ |   \ \ / // /      #
#   | |__| | |  | |_| | (_| \__ \ | \ \| |    | |__| |    \ V // /_      #
#   |_____/|_|   \__,_|\__, |___/_|  \_\_|     \_____|     \_/|____|     #
#                       __/ |                                            #
#                      |___/                                             #
#                                                                        #
##########################################################################

# The best and most customisable drugs plugin on the market.
# Created with love by rndstad.me
# Please leave a 5-star rating on the DrugsRPG spigot page.

## General Settings ##
preferences:
  use-mysql: true
  host: localhost
  port: 3306
  database: drugsrpg_drugs
  username: ""
  password: ""