name: DrugsRPG
author: Randstad
version: 2.0
main: me.rndstad.drugsrpg.Core
description: The best drugs plugin on the market, created by rndstad.me
website: http://rndstad.me
commands:
   drugs:
   