name: DrugsRPG
author: Randstad
version: 2.2
main: me.rndstad.drugsrpg.Core
description: The best drugs plugin on the market, created by rndstad.me
website: http://rndstad.me
softdepend: [PlaceholderAPI]
commands:
   drugs:
   